name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: needs write permissions to commit back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: PrajjwalDatir # Your GitHub username
          # List of SVG output files with optional additional parameters
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          # Enable this if you want to use a different branch for the output files
          # target_branch: output 

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist # or the svg_out_path configured above
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Generate Contribution Snake"
            git push
          else
            echo "No changes to commit for snake animation."
          fi
        # If you are using a target_branch other than the one the workflow runs on:
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Default token
